name       : libassuan
version    : 2.5.3
release    : 8
source     :
    - https://www.gnupg.org/ftp/gcrypt/libassuan/libassuan-2.5.3.tar.bz2 : 91bcb0403866b4e7c4bc1cc52ed4c364a9b5414b3994f718c70303f7f765e702
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : security
summary    : IPC library used by some GnuPG related software
description: |
    Libassuan is the IPC library used by some GnuPG related software.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
