name       : libassuan
version    : 2.5.1
release    : 6
source     :
    - https://www.gnupg.org/ftp/gcrypt/libassuan/libassuan-2.5.1.tar.bz2 : 47f96c37b4f2aac289f0bc1bacfa8bd8b4b209a488d3d15e2229cb6cc9b26449
license    :
    - GPL-3.0
    - LGPL-2.1
component  : security
summary    : IPC library used by some GnuPG related software
description: |
    Libassuan is the IPC library used by some GnuPG related software.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
