name       : libassuan
version    : 2.4.3
release    : 4
source     :
    - https://www.gnupg.org/ftp/gcrypt/libassuan/libassuan-2.4.3.tar.bz2 : 22843a3bdb256f59be49842abf24da76700354293a066d82ade8134bb5aa2b71
license    :
    - GPL-3.0
    - LGPL-2.1
component  : security
summary    : IPC library used by some GnuPG related software
description: |
    Libassuan is the IPC library used by some GnuPG related software.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
